title: ðŸŒµ US Drought Monitor Archive
description: An archive of the US Drought Monitor weekly drought assessment
author: R. Kyle Bocinsky
url: "https://sustainable-fsa.com/usdm/" # Your GitHub Pages URL
baseurl: "/usdm"

remote_theme: jekyll/minima
plugins:
  - jekyll-remote-theme
# minima:
#   skin: classic
